### PR TITLE
Add PremierProfiles call

### PR DESCRIPTION
**Pull request by ncsmikewoods**
Added an extension method for the PremierProfiles API.

Note: The PremierProfilesResponse is incomplete.  This file should be considered something like a starting point implementation.  I wasn't sure how much reuse of the internal structure you'd want so I kept the nested objects in the same file.  Also, the majority of the properties are not present as they were not relevant to what I needed.

### CODE REVIEW

**Comment by Lexcess** [comment]
Merging into a separate branch so the work can be completed and merged to master.

**Comment by Lexcess** [comment]
Thanks for the heads up. We'll modify that when we split out the classes and finish off the attributes. 

If you didn't know, until it is merged, you can continue to update a PR by making commits to the source branch. So feel free to do so in the future.

**Comment by ncsmikewoods** [comment]
Yeah I intended to just got caught up in other things :)  

Thanks for the heads up though.

**Comment by Lexcess** [comment]
No problem. I'm not sure when we'll have the feature finished and tested but you can track the work here: https://github.com/experianplc/experian-dotnet/tree/PremierProfilesUpdate I've already made that change to API Extensions you highlighted.

**Pull request merged**
